baseurl = "https://zapfev.de/"
languageCode = "de-DE"
title = "ZaPF e.V."

theme = "zapf"

[params]
# You can use markdown here.
brand = "ZaPF e.V."
topline = "Zusammenkunft aller Physik-Fachschaften"

# Sidebar position
# false, true, "left", "right"
sidebar = "left"

# Text for the top menu link, which goes the root URL for the site.
# Default (if omitted) is "Home".
home = "Home"

# Select a syntax highight.
# Check the static/css/highlight directory for options.
highlight = "default"

# Sidebar social links.
github = "ZaPF" # Your Github profile ID
